apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guiss0api-java
  template:
    metadata:
      labels:
        app: guiss0api-java
    spec:
      containers:
        - name: api-java
          image: guiss0/$IMAGE_NAME:imageversion  # Imagen de Docker Hub desde los secretos de GitHub Actions
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-java
spec:
  selector:
    app: guiss0api-java
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
  type: NodePort
